apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: flexvolume-qemu-nbd
  namespace: kube-system
spec:
  template:
    metadata:
      name: flexvolume-qemu-nbd
      labels:
        app: flexvolume-qemu-nbd
    spec:
      restartPolicy: OnFailure
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
        - image: kvaps/flexvolume-qemu-nbd:latest
          imagePullPolicy: Always
          name: flexvolume-qemu-nbd
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
