apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nbd-flexvolume
  namespace: kube-system
spec:
  template:
    metadata:
      name: nbd-flexvolume
      labels:
        app: nbd-flexvolume
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
        - image: kvaps/kube-loop-flexvolume:nbd
          name: nbd-flexvolume
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-mount
      volumes:
        - name: flexvolume-mount
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
