apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "kvaps/qemu-nbd"
      fsType: "ext4"
      options:
        share: "/stor/beegfs-1"
        file: "/kube-volumes/test"
        size: "1g"
